### ISSUE TITLE
Get study article for this week

### ISSUE THREAD

**Issue by GeiserX** [MrCyjaneK/jwapi#27]
Hey. I'm requesting a little bit help from you as you seem to be the most knowledgeable related to the JW API.
I'm trying to get this weeks' Watchtower, but it seems to be mission impossible (regarding to `catalog.db`). I can retrieve the Publication, but the mission is to get the correct DocumentID. There is a table there PublicationDocument but there is no relationship to the week. A given publication has many documentId. I can retrieve the index of the Watchtower for the month, but that't it.
I've checked and this could be feasible with docClass (As I'm seeing on the web) but it's nowhere to be seen in any db.
What's your approach for this? Highly appreciate your help.

**Comment by orangethewell** [comment]
There is `DatedDocument` table for every dated study. This a sample for the exact day (or week) of the entire publication document. I don't remember if `DatedDocument` from watchtower articles contains the study or a page with a `jwpub://` link to study... but at all, all studies with dated content are set in this table. Ex: Daily text for the exact day is set there, while `Document` table holds data for the entire month.

The date string is formatted with "yearMonthDay" if i'm not mistaken, and for checking if is in the current week, just check if it is between `startDate` and `endDate`, that for study articles covers one week instead of one day.

**Comment by GeiserX** [comment]
Thanks @orangethewell for your time.

There is `DatedText` table which in fact I was trying to use, but it just contains the `PublicationId`s for the entire month, but I can't find `DatedDocument` or `Document` tables you mentioned. Perhaps I need other file I didn't fetch?... There are few "weekly" rows in `DatedText` but only for a few rare languages, and I prefer not to use it. 

[Here using this function](https://github.com/GeiserX/jwlibrary-plus/blob/main/src/bot_ng.py#L376-L483) is how I currently extract it, as I found it impossible to do it via only the sqlite db. I extract the index and visit the URL, then I extract the "nth" link which belongs to a given class. A bit hacky, but haven't found any workaround yet.

**Comment by orangethewell** [comment]
Sorry, misspelled the name, it is `DatedText`, you just need to decrypt content using the same method for decrypt content column from Document. At least, it doesn't exist on catalog.db, which seems to be the db you looking for, there's only the publicationId for you looking out on publications and get it. The DatedText content is in the own publication db file (*.jwpub/content/*.db)

**Comment by GeiserX** [comment]
Okay, thanks a lot for your help. Then I will try to do it differently I believe, as I was interfacing directly with the web through `catalog.db`. Instead, I will just download the `.jwpub` file and work with the contents, that's a better approach. I had previously gained experience from getting data from `.jwpubs` so this will get handy. Hopefully I can get the data about the week.
Thank you!
